---
master_hostname: 'kube-master01.spider.com'
docker_daemon_file: | 
  {
    "exec-opts": ["native.cgroupdriver=systemd"],
    "log-driver": "json-file",
    "log-opts": {
      "max-size": "100m"
    },
    "storage-driver": "overlay2",
    "storage-opts": [
      "overlay2.override_kernel_check=true"
    ]
  }

kubernetes_repo_file: |
  [kubernetes]
  name=Kubernetes
  baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
  enabled=1
  gpgcheck=1
  repo_gpgcheck=1
  gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg


kubernete_sysctl_file: |
  net.bridge.bridge-nf-call-ip6tables = 1
  net.bridge.bridge-nf-call-iptables = 1

control_node_isworking: True

cluster_endname: k8s.spider.com

cluster_token: 7bef73.xo5ovzdknrjhmzc0

cluster_sha: sha256:459a4d80050468281bb4e1484ee42ad361eba542a81d3b388552bb87969f4898

worker_node_new: new


