---
- name: install
  package: name=postgresql state=present

- name: configure
  copy:
    src: postgresql.conf
    dest: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644
  notify: 
    - restart postgresql

- name: service
  service: name=postgresql state=started enabled=yes

- meta: flush_handlers

- name: users
  become: true
  become_user: postgres
  postgresql_user:
    name: "debuger"
    password: "changeme"
