---

- hosts: databases
  become: true
  remote_user: badmin
  roles: 
    - role: postgresql
  tags: prod-psql

- hosts: databases
  become: true
  remote_user: badmin
  roles: 
    - role: useradd
  tags: cusr

- hosts: all
  become: true
  remote_user: badmin
  roles:
    - role: common
    - role: debug
      me: 'roles.yaml'
  tags: all-com

- hosts: webservers
  become: true
  remote_user: badmin
  roles:
   - role: apache-server
   - role: apache-config
  tags: test-web


- hosts: databases
  become: yes
  remote_user: badmin
  roles:
    - role: mysql-server
  tags: test-mysql

- hosts: all
  become: true
  remote_user: badmin
  roles:
    - statexample
  tags: stat 

- hosts: all
  become: true
  remote_user: badmin
  roles:
    - jinjaexample
  tags: jinja 

- hosts: all
  become: true
  remote_user: badmin
  roles:
    - changepw
  tags: pw

- hosts: localhost
  become: true
  roles:
    - awx
  tags: awx
