---
- hosts: all
  become: true
  tasks:
    - name: "line in edit"
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: '127.0.0.1 localhost'
        owner: root
        group: root
        mode: 0644
        
