---
- name: Add tower machine credential
  tower_credential:
    name: "{{ my_credential_name }}"
    username: "{{ my_admin_username }}"
    password: "{{ my_admin_password }}"
    organization: "{{ my_org_name }}"
    become_method: sudo
    become_password: "{{ my_admin_password }}"
    become_username: root
    state: present
    kind: ssh
    tower_host: 'http://192.168.20.145'
    tower_username: admin
    tower_password: "{{ my_tower_password }}"
    validate_certs: false
#    tower_config_file: "/root/.awxenv2"
