---
# tasks file for apache2modify

- name: "copy index.html"
  copy:
    src: "index.html"
    dest: "/var/www/html/index.html"
    owner: "www-data"
    group: "www-data"
    mode: 0644
  notify:
    - restart apache2
