---
# tasks file for haproxymodify


- name: haproxy ssl file
  copy:
    content: "{{ haproxy_ssl_cert }}"
    dest: /etc/ssl/haproxy.pem
    owner: root
    group: root
    mode: 0600
  when: haproxy_ssl_cert is defined


- name: copy haproxy config
  template:
    src: haproxy.http.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart haproxy

- debug:
    msg: "This debug message came from {{ me|default('roles/haproxymodify/tasks/main.yaml') }}"

