---

# Main tasks file for sftp role

- name: 'Add sftp group'
  become: true
  group:
    name: "{{ sftp_group_name }}"
    state: 'present'


- name: 'Create sftp data path'
  become: true
  file:
    path: "{{ sftp_data_dir_path }}"
    owner: "{{ sftp_data_dir_owner }}"
    group: "{{ sftp_data_dir_group }}"
    mode: "{{ sftp_data_dir_mode }}"
    state: 'directory'


- name: 'Add sftp users'
  become: true
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default(sftp_group_name) }}"
    createhome: true
    home: "{{ item.home_path | default(sftp_data_dir_path ~ '/' ~ item.name) }}"
    skeleton: "{{ item.skeleton | default(sftp_users_skeleton) }}"
    state: "{{ item.state | default('present') }}"
    shell: "{{ item.shell | default(sftp_users_shell) }}"
    password: "{{ item.password }}"
  no_log: False
  with_items: "{{ sftp_users }}"


- name: 'USERS | Manage permissions on users home directory'
  become: True
  file:
    path: "{{ item.home_path | default(sftp_data_dir_path ~ '/' ~ item.name) }}"
    owner: "{{ item.home_owner | default(sftp_data_dir_owner) }}"
    group: "{{ item.home_group | default(item.name) }}"
    mode: "{{ item.home_mode | default(sftp_users_home_mode) }}"
  no_log: False
  with_items: "{{ sftp_users }}"
  when: "(item.state | default('present')) == 'present'"

- name: 'Configure sshd_config for sftp user and group'
  become: true
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Subsystem sftp internal-sftp
      Match Group sftptest
        X11Forwarding no
        AllowTcpForwarding no
        ChrootDirectory %h
        ForceCommand internal-sftp
        PermitTunnel no
        AllowAgentForwarding no
  notify: 'restart_ssh' 


  
